name: Build and Release Index Management
on:
  push:
    branches:
      - opendistro-*

jobs:
  Release-Index-Management:
    strategy:
      matrix:
        java: [12]

    name: Build and Release Index Management
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Index Management
        uses: actions/checkout@v1
        
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Run build
        run: |
          ./gradlew build buildDeb buildRpm --console=plain -Dbuild.snapshot=false
          artifact=`ls build/distributions/*.zip`
          rpm_artifact=`ls build/distributions/*.rpm`
          deb_artifact=`ls build/distributions/*.deb`
          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/opendistro-index-management/
          aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-index-management/
          aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-index-management/
          aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/*"
